---
# file: admin_client.yml

- hosts: localhost
  connection: local
  roles:
  - common
  - dnssec_validation
  - local_users
  - fedora_rpm_fusion
  - sensitive_data
  - subversion_repos
  - ldap_browser

