# file: roles/local_users/tasks/main.yaml
---

- name: Local user accounts
  with_dict: "{{ local_users | default([]) }}"
  become: yes
  user: name="{{ item.key }}"
        comment="{{ item.value.fullname }}"
        append=yes
        groups="{{ item.value.groups | default([]) }}"
        shell="{{ item.value.shell | default('/bin/bash') }}"
        generate_ssh_key=yes
        ssh_key_bits="{{ ssh_key_bits | default(4096) }}"
        ssh_key_type="{{ ssh_key_type | default('rsa') }}"
        ssh_key_comment="{{ item.key }}@{{ ansible_fqdn
                         }}-{{ ansible_date_time.iso8601 | replace(':', '') }}"
        state=present

- name: Configure sudoers
  with_items:
    - regexp: '^%wheel\s+ALL='
      line: '%wheel ALL=(ALL) NOPASSWD:ALL'
    - regexp: '^Defaults\s+secure_path'
      line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin'
  become: yes
  lineinfile: dest=/etc/sudoers state=present regexp="{{ item.regexp }}" line="{{ item.line }}" validate='visudo -qcf %s'

- name: Local user workspace directories
  with_dict: "{{ local_users }}"
  file: state=directory
        path=/home/{{ item.key }}/workspace
        owner="{{ item.key }}" group="{{ item.key }}"

- name: Local user Git configurations
  with_dict: "{{ local_users }}"
  template: src=gitconfig.j2
            dest="/home/{{ item.key }}/.gitconfig"
            owner="{{ item.key }}" group="{{ item.key }}" mode=0664
            force=no

- name: Local user Maven settings directories
  with_dict: "{{ local_users }}"
  become: yes
  file: state=directory
        path="/home/{{ item.key }}/.m2"
        owner="{{ item.key }}" group="{{ item.key }}"

- name: Local user Maven settings
  with_dict: "{{ local_users }}"
  become: yes
  template: src=settings.xml.j2
            dest="/home/{{ item.key }}/.m2/settings.xml"
            owner="{{ item.key }}" group="{{ item.key }}" mode=0660
            force=no backup=yes
