---
# file: roles/sensitive_data/tasks/main.yml

# Sensitive data management allows deploying and backing up private credentials
# such as digital certificates, private key materials, and password files
# without writing them in clear text.

- yum: pkg=cryptsetup state=present

- name: Sensitive data management initialization script
  sudo: yes
  template: src=init_sensitive_data.j2
            dest=/usr/local/sbin/init_sensitive_data
            owner=root group=root mode=0700

- name: Sensitive data volume opening script
  sudo: yes
  template: src=open_sensitive_data.j2
            dest=/usr/local/sbin/open_sensitive_data
            owner=root group=root mode=0700

- name: Sensitive data volume closing script
  sudo: yes
  template: src=close_sensitive_data.j2
            dest=/usr/local/sbin/close_sensitive_data
            owner=root group=root mode=0700

#
# Use an absolute path for the Ansible Vault password file
# to allow it work with any user who has access to the file.
#
- name: Ansible Vault password file location
  sudo: yes
  lineinfile: dest=/etc/ansible/ansible.cfg
              regexp='^vault_password_file\s*=.*$'
              line='vault_password_file = /root/.vault_pass.txt'
