---
# file: roles/dnssec_validation/tasks/main.yml

#
# DNSSEC validating resolver and SSHFP host key verification
#

- name: Local DNS resolver trusted for the DNSSEC validation
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 20
  yum: name=dnssec-trigger

- name: Enable EDNS0
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 20
  lineinfile: dest=/etc/profile.d/resolv.sh
              create=yes
              regexp="^.*RES_OPTIONS=.*$"
              line="export RES_OPTIONS=edns0"

- name: Enable DNSSEC validation
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 20
  service: name=dnssec-triggerd enabled=yes state=started

- name: Enable SSH host key DNS verification (SSHFP)
  sudo: yes
  lineinfile: dest=/etc/ssh/ssh_config regexp="^VerifyHostKeyDNS" line="VerifyHostKeyDNS yes" state=present

