# file: roles/ldap_browser/tasks/main.yml
#
# http://jxplorer.org/downloads/
#
---

- set_fact:
    jxplorer_archive: "jxplorer-3.3.1-project.zip"
    jxplorer_md5sum: "bf58eccc7fe5c323a2ecce52c237bd13"

- set_fact:
    jxplorer_url: "http://sourceforge.net/projects/jxplorer/files/jxplorer/version%203.3.1/{{ jxplorer_archive | mandatory }}/download"

- name: Download the JXplorer archive
  become: yes
  command: chdir=/opt
           creates="{{ jxplorer_archive | mandatory }}"
           wget -nv --no-cookies --no-check-certificate
           "{{ jxplorer_url | mandatory }}" -O "{{ jxplorer_archive }}"

- name: Verify the JXplorer archive
  become: yes
  stat: path="/opt/{{ jxplorer_archive }}"
  register: jxplorer
  failed_when: jxplorer.stat.md5 != "{{ jxplorer_md5sum | mandatory }}"

- name: Self-executable JXplorer archive
  become: yes
  file: path="/opt/{{ jxplorer_archive }}" mode=774

# Run the installer manually.
