# file: roles/common/tasks/main.yml

- name: Enable Ansible under SELinux
  sudo: yes
  yum: pkg=libselinux-python state=present

- name: Local DNS resolver trusted for the DNSSEC validation
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 20
  yum: pkg=dnssec-trigger state=present

- name: Enable DNSSEC validation
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 20
  service: name=dnssec-triggerd enabled=yes state=started

- name: Single Packet Authentication (SPA) support
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 14
  yum: pkg=fwknop state=present

- name: Non-interactive SSH password authentication support
  sudo: yes
  yum: pkg=sshpass state=present

- yum: pkg=firewalld state=present
- yum: pkg=gdb state=present
- yum: pkg=git state=present
- yum: pkg=gnupg state=present
- yum: pkg=htop state=present
- yum: pkg=jwhois state=present
- yum: pkg=lftp state=present
- yum: pkg=man state=present
- yum: pkg=maven state=present
- yum: pkg=nano state=present
- yum: pkg=postgresql state=present
- yum: pkg=python-boto state=present
- yum: pkg=rkhunter state=present
- yum: pkg=screen state=present
- yum: pkg=wget state=present
- service: name=firewalld enabled=yes state=started
