# file: roles/common/tasks/main.yml
---

- name: Dandified Yum
  when: ansible_pkg_mgr == "yum"
  become: yes
  yum: name="dnf"

- name: Ansible DNF dependencies
  when: ansible_pkg_mgr == "yum"
  become: yes
  with_items:
  - python2-dnf
  yum: name="{{ item }}"

- name: DNF system upgrade plugin
  become: yes
  dnf: name="dnf-plugin-system-upgrade"

- name: Enable Ansible under SELinux
  become: yes
  dnf: name="libselinux-python"

- name: Single Packet Authentication (SPA) support
  become: yes
  when: ansible_distribution == "Fedora" and
        ansible_distribution_version|int >= 14
  dnf: name="fwknop"

- name: Non-interactive SSH password authentication support
  become: yes
  dnf: name="sshpass"

- name: Common packages
  with_items:
  - colordiff
  - emacs
  - firewalld
  - gdb
  - gimp
  - git
  - gnupg
  - htop
  - iotop
  - jwhois
  - keepass
  - lftp
  - lookup
  - lshw
  - lv
  - man
  - maven
  - midori
  - nano
  - parallel
  - postgresql
  - pv
  - python2-boto
  - python2-passlib
  - python-cffi
  - python-dns
  - python-firewall
  - python-netaddr
  - rkhunter
  - screen
  - sysstat
  - wget
  become: yes
  dnf: name="{{ item }}"

- name: Enable Firewall
  become: yes
  service: name="firewalld" enabled=yes

- name: Start Firewall
  become: yes
  service: name="firewalld" state=started

- name: HArdware Volatile Entropy Gathering and Expansion (HAVEGE) daemon
  become: yes
  dnf: name="haveged"

- name: Enable the entropy service
  become: yes
  service: name="haveged" enabled=yes

- name: Start the entropy service
  become: yes
  service: name="haveged" state=started

#
# http://keyring.debian.org/creating-key.html
#
- name: Configure GnuPG
  with_items:
  - key: personal-digest-preferences
    val: SHA256
  - key: cert-digest-algo
    val: SHA256
  - key: default-preference-list
    val: SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
  lineinfile: dest="~/.gnupg/gpg.conf"
              regexp="^{{ item.key }}"
              line="{{ item.key }} {{ item.val | mandatory }}"
              insertafter=EOF
              create=yes
              state=present
