---
# file: roles/common/tasks/main.yml

- name: Enable Ansible under SELinux
  sudo: yes
  yum: name=libselinux-python

- name: Local DNS resolver trusted for the DNSSEC validation
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 20
  yum: name=dnssec-trigger

- name: Enable DNSSEC validation
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 20
  service: name=dnssec-triggerd enabled=yes state=started

- name: Enable SSH host key DNS verification (SSHFP)
  lineinfile: dest=/etc/ssh/ssh_config regexp="^VerifyHostKeyDNS" line="VerifyHostKeyDNS yes" state=present

- name: Single Packet Authentication (SPA) support
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 14
  yum: name=fwknop

- name: Non-interactive SSH password authentication support
  sudo: yes
  yum: name=sshpass

- name: Common packages
  with_items:
  - firewalld
  - gdb
  - git
  - gnupg
  - htop
  - jwhois
  - lftp
  - lookup
  - lv
  - man
  - maven
  - nano
  - postgresql
  - pv
  - python-boto
  - rkhunter
  - screen
  - wget
  sudo: yes
  yum: name={{ item }}

- service: name=firewalld enabled=yes state=started

- name: HArdware Volatile Entropy Gathering and Expansion (HAVEGE) daemon
  sudo: yes
  yum: name=haveged

- name: Enable the entropy service
  sudo: yes
  service: name=haveged enabled=yes state=started

#
# http://keyring.debian.org/creating-key.html
#
- name: Configure GnuPG
  with_items:
  - key: personal-digest-preferences
    val: SHA256
  - key: cert-digest-algo
    val: SHA256
  - key: linedefault-preference-list
    val: SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
  lineinfile: dest="~/.gnupg/gpg.conf"
              regexp="^{{ item.key }}"
              line="{{ item.key }} {{ item.val | mandatory }}"
              insertafter=EOF
              state=present
