---
# file: roles/common/tasks/main.yml

- name: Dandified Yum
  sudo: yes
  yum: name=dnf

- name: Enable Ansible under SELinux
  sudo: yes
  dnf: name=libselinux-python

- name: Single Packet Authentication (SPA) support
  sudo: yes
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 14
  dnf: name=fwknop

- name: Non-interactive SSH password authentication support
  sudo: yes
  dnf: name=sshpass

- name: Common packages
  with_items:
  - firewalld
  - gdb
  - gimp
  - git
  - gnupg
  - htop
  - jwhois
  - keepass
  - lftp
  - lookup
  - lshw
  - lv
  - man
  - maven
  - midori
  - nano
  - postgresql
  - pv
  - python-boto
  - python-passlib
  - rkhunter
  - screen
  - sysstat
  - wget
  sudo: yes
  dnf: name={{ item }}

- name: Enable Firewall
  sudo: yes
  service: name=firewalld enabled=yes state=started

- name: HArdware Volatile Entropy Gathering and Expansion (HAVEGE) daemon
  sudo: yes
  dnf: name=haveged

- name: Enable the entropy service
  sudo: yes
  service: name=haveged enabled=yes state=started

#
# http://keyring.debian.org/creating-key.html
#
- name: Configure GnuPG
  with_items:
  - key: personal-digest-preferences
    val: SHA256
  - key: cert-digest-algo
    val: SHA256
  - key: default-preference-list
    val: SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
  lineinfile: dest="~/.gnupg/gpg.conf"
              regexp="^{{ item.key }}"
              line="{{ item.key }} {{ item.val | mandatory }}"
              insertafter=EOF
              create=yes
              state=present

