---
# file: roles/common/tasks/smart_cards.yml

- name: Smart Card support packages
  with_items:
  - esc
  - pam_pkcs11
  - coolkey
  - ccid
  - gdm
  - authconfig
  - authconfig-gtk
  - opensc
  - mozilla-esteid
  sudo: yes
  yum: name={{ item }}

- name: Enable the Smart Card reader
  sudo: yes
  service: name=pcscd enabled=yes state=started

