# file: roles/fedora_rpm_fusion/tasks/main.yaml
---

- name: Check enabled repositories
  command: dnf repolist enabled
  register: dnf_repolist
  changed_when: False

- name: Enable the RPM Fusion repositories for Fedora 14 and above
  when: not 'rpmfusion' in dnf_repolist.stdout and
        ansible_distribution_version|int >= 14
  with_items:
  - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
  - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
  become: yes
  dnf:
    name: "{{ item }}"
    disable_gpg_check: yes
